name: deployment dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on:
      - self-hosted
      - dev-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-express:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/demo-express:latest

  pull:
    needs: build
    runs-on:
      - self-hosted
      - dev-server
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demo-express:latest

  deploy:
    needs: pull
    runs-on:
      - self-hosted
      - dev-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker compose up
        run: docker compose build && docker compose up -d
